### ISSUE TITLE
doesn't define Compose global

### ISSUE THREAD

**Issue by wkeese** [kriszyp/compose#13]
I thought ComposeJS supports just loading the compose.js file, without having an AMD framework.   But when I try it in firefox (version 10, beta) or the latest chrome, I get an error about the Compose global being not defined.    Test file is:

``` html
<html>
    <head>
        <script src="compose.js"></script>
        <script>
            console.log("Compose global is", Compose);
        </script>
    </head>
</html>
```

**Comment by neonstalwart** [comment]
the problem is that the placement of `"use strict";` won't allow for a global to be made.
