### ISSUE TITLE
IE | Extending method to constructor will FAIL when the method name is the same as one of built-in Object.prototype methods

### ISSUE THREAD

**Issue by normanzb** [kriszyp/compose#21]
Please run this test on REAL IE8 and compare it with the other modern browser:

http://jsfiddle.net/ukrFb/3/

Caveat: Do not use IE9's IE8 mode for testing, it CANNOT reproduce the issue!

Expected Result:

"a" in the result window

Actual Result in IE 8:

"[Object object]"
# 

The cause of this issue is that if the member name of an object is same as the one of the bulti-in method name of Object.prototype.

it became un-enumerable!!

run below code in IE8 to see the bug:

var test = {toString:function(){}, foobar: function(){}};

for(var key in test){console.log(key)}

**Comment by kriszyp** [comment]
This is a known issue with a known resolution, but the fix has a larger performance and space impact than acceptable for the performance priorities of Compose.
