### ISSUE TITLE
subclassing Error

### ISSUE THREAD

**Issue by neonstalwart** [kriszyp/compose#4]
is it possible to support subclassing Error so that this can be done
    var CustomError = Compose(Error, function (msg) {
        this.message = 'custom ' + this.foo + msg; 
    }, { 
        foo: 'foo'
    });
    var err = new CustomError('bar');
    console.log(err);
    console.log(err instanceof CustomError ? 'yes' : 'no');

currently, `instanceof` returns false and `foo` is not mixed in.  i found this blog post (http://blog.getify.com/2010/02/howto-custom-error-types-in-javascript/) about subclassing Error if it's useful for reference.

**Comment by kriszyp** [comment]
Fixed in last commit.
