### ISSUE TITLE
Post-construction callbacks?

### ISSUE THREAD

**Issue by novemberborn** [kriszyp/compose#6]
I have a `TextBox` widget extending `dojo/on#Evented`. It emits a `change` event every time its value changes. I'm subclassing it into a `ValidationTextBox` widget, where I'd like to listen to `change` events to run validation code. I'd like to use a decorator to set up a `_validate` function which is automatically listening to the `change` event:

``` js
define([
  "./TextBox",
  "decorators"
], function(TextBox, decorators){
  return TextBox.extend({
    validate: function(){
      return this._validate(this.get("value"));
    },

    isValid: function(value){
      return true;
    },

    _validate: decorators.on("change", function(value){
      return this.isValid(value);
    })
  });
});
```

Initially, my decorator looked like this:

``` js
define([
  "dojo",
  "compose"
], function(dojo, Compose){
  return {
    on: function(type, listener){
      return new Compose.Decorator(function(key){
        this[key] = listener;
        this.on(type, dojo.hitch(this, key));
      });
    }
  };
});
```

But this won't work, since inside the decorator, `this` refers to the prototype. My workaround is to use after-advice around the `postCreate` method:

``` js
define([
  "dojo",
  "compose"
], function(dojo, Compose){
  return {
    on: function(type, listener){
      return new Compose.Decorator(function(key){
        this[key] = listener;

        Compose.after(function(){
          this.on(type, dojo.hitch(this, key));
        }).install.call(this, "postCreate");
      });
    }
  };
});
```

That works, but is a bit cumbersome. It'd be nice if Composed classes could signal when their constructors have finished running to provide a reference to the created instance, for example:

``` js
define([
  "dojo",
  "compose"
], function(dojo, Compose){
  return {
    on: function(type, listener){
      return new Compose.Decorator(function(key){
        this[key] = listener;
        this["-created-"](function(){
          this.on(type, dojo.hitch(this, key));
        });
      });
    }
  };
});
```

Thoughts?

**Comment by kriszyp** [comment]
It seems like the ideally the first example should work. I think you should be able to delegate to an object that already has a listener bound to it. I think there may be a bug in dojo/aspect that prevents this from working correctly.

**Comment by novemberborn** [comment]
Compose doesn't pick up on `dojo/aspect` though does it?

The issue is that decorators are applied to the prototype (which makes sense to me), but I need to run this particular decorator on instances instead. When I call `this.on(type, dojo.hitch(this, key))` I call it on the prototype.

**Comment by kriszyp** [comment]
Oh, right, I was looking at the problem with calling on() on the prototype. The dojo.hitch problem can be solved by using the |this| in the callback. With dojo/aspect fixed (working on a fix ATM), hopefully you should be able to write:

```
on: function(type, listener){
  return new Compose.Decorator(function(key){
    this[key] = listener;
    this.on(type, function(){
      // |this| will be the instance when the instance emits the event
      listener.apply(this, arguments);
    });
  });
}
```

**Comment by kriszyp** [comment]
dojo/aspect (and thus dojo/on) should be fixed in r25466

**Comment by novemberborn** [comment]
Cool. I'll have to wait for the Dojo repo here on GitHub to update, so will try tomorrow.

Aside from that, would it make sense for Compose to have post-construction callbacks?

**Comment by novemberborn** [comment]
Your example worked great, thanks.

**Comment by kriszyp** [comment]
I'd like to avoid additions to Compose unless it is really necessary.
